version = 0.1
[debug]
enabled = true

[bastion]
max_health = 50.0
movement_speed = 0.30
attack_damage = 12.0
follow_range = 30.0
armor = 14.0
armor_toughness = 0.7
knockback_resistance = 0.1

[blindwrath]
max_health = 40.0
movement_speed = 0.32
attack_damage = 8.0
follow_range = 30.0
armor = 12.0
armor_toughness = 0.7
knockback_resistance = 0.1

[blindwrath.sonicbeam]
max_cooldown = 30
aggro_range = 20
attack_range = 10
damage = 10.0
vertical_knock_constant = 0.5
horizontal_knock_constant = 2.5

[hollowseer]
max_health = 40.0
movement_speed = 0.32
attack_damage = 8.0
follow_range = 30.0
armor = 10.0
armor_toughness = 0.7
knockback_resistance = 0.1

[hollowseer.evoker_fang_beam]
number_of_fangs = 20
max_cooldown = 30
aggro_range = 20
attack_range = 15

[hollowseer.cursed_bullet]
max_cooldown = 60
range_of_activation = 16
min_shooting_distance = 40
status_effect = "minecraft:blindness"
effect_duration = 40
effect_amplifier = 1

[plaguebrute]
max_health = 50.0
movement_speed = 0.30
attack_damage = 8.0
follow_range = 30.0
armor = 12.0
armor_toughness = 0.7
knockback_resistance = 0.1

[plaguebrute.sonicboom]
max_cooldown = 30
aggro_range = 15
attack_range = 10
damage = 10.0
vertical_knock_constant = 2
horizontal_knock_constant = 1.5

[reaver]
max_health = 40.0
movement_speed = 0.32
attack_damage = 12.0
follow_range = 30.0
armor = 12.0
armor_toughness = 0.7
knockback_resistance = 0.1

[reaver.evoker_fang_circle]
number_of_fangs = 5
number_of_circles = 4
radius_step = 1.0
max_cooldown = 60
aggro_range = 10
attack_range = 7

[red_blood_mage]
max_health = 10.0
movement_speed = 0.30
attack_damage = 4.0
follow_range = 30.0
armor = 10.0
armor_toughness = 0.7
knockback_resistance = 0.1

[red_blood_mage.blood_beam]
max_cooldown = 20
aggro_range = 20
attack_range = 10
damage= 5
attraction_strength= 1.5


[stalker]
max_health = 50.0
movement_speed = 0.35
attack_damage = 8.0
follow_range = 30.0
armor = 14.0
armor_toughness = 0.7
knockback_resistance = 0.1


# MEME
[bard]
max_health = 20.0
movement_speed = 0.33
attack_damage = 8.0
follow_range = 30.0
armor = 12.0
armor_toughness = 0.7
knockback_resistance = 0.1

[bard.sonicbeam]
max_cooldown = 30
aggro_range = 15
attack_range = 10
damage = 10.0
vertical_knock_constant = 2
horizontal_knock_constant = 1.5

[tobias]
max_health = 20.0
movement_speed = 0.33
attack_damage = 8.0
follow_range = 30.0
armor = 12.0
armor_toughness = 0.7
knockback_resistance = 0.1